### ISSUE TITLE
Readme could be updated

### ISSUE THREAD

**Issue by zameel7** [zameel7/todo-list#1]

**Comment by Supratim30** [comment]
Hey, would like to work on this. Please assign it to me.

**Comment by zameel7** [comment]
@Supratim30 , you may make changes and send a PR.
I'll look into it and merge if it's good

**Comment by Supratim30** [comment]
#5 Generated a PR for the issue.

**Comment by aankitasoni** [comment]
please assign this to me @zameel7

**Comment by zameel7** [comment]
@aankitasoni , do make changes and make a PR. I'll merge those
