### ISSUE TITLE
UI: navbar doesn't look quite good

### ISSUE THREAD

**Issue by zameel7** [zameel7/todo-list#2]

**Comment by ankit060801** [comment]
Please assign me this task!!

**Comment by zameel7** [comment]
> Please assign me this task!!

@ankit060801 , thank you for your contribution!

**Comment by aankitasoni** [comment]
please  assign this to me @zameel7

**Comment by zameel7** [comment]
@aankitasoni , do make changes and make a PR and I'll ad those changes.
